apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
spec:
  kafka:
    version: 3.2.3
    replicas: 3 # 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
#      - name: tls
#        port: 9093
#        type: loadbalancer
#        tls: true
#        authentication:
#          type: tls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
      log.retention.ms: 60000
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: true
    resources:
      requests:
        memory: 2500Mi # 4Gi
        cpu: 1000m
      limits:
        memory: 1500Mi
        cpu: 4000m
  zookeeper:
    replicas: 1 # 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    resources:
      requests:
        memory: 500Mi # 2Gi
        cpu: 1000m
      limits:
        memory: 16Gi
        cpu: 2000m
  entityOperator:
    userOperator:
      resources:
        requests:
          memory: 500Mi
          cpu: 250m
        limits:
          memory: 8000Mi
          cpu: 4000m
    topicOperator: 
      resources:
        requests:
          memory: 500Mi
          cpu: 250m
        limits:
          memory: 8000Mi
          cpu: 4000m