apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
spec:
  replicas: 4 # 1
  bootstrapServers: my-kafka-kafka-bootstrap:9092
  http:
    port: 8082
  resources:
    requests:
      memory: 9000Mi
      cpu: 4000m